name: GitHub Actions Demo

on:
  push:
    branches: main
    paths-ignore: .github

  schedule:
    - cron: 15 6 * * 0

  workflow_dispatch:

jobs:
  Build:
    name: build job
    runs-on: ubuntu-latest
    
    steps:
      - run: echo " ${{ github.event_name }} "
      - run: echo " ${{ github.ref }} "
      - uses: actions/checkout@v3.3.0
      - run: tree
    
